Added resource_info.go
k82cn/kube-arbitrator pull request #31
Opened 2017-09-17 05:13 UTC by swiftdiaries

Addressing issue: https://github.com/kubernetes-incubator/kube-arbitrator/issues/29.

2017-09-17 05:44 UTC, swiftdiaries commented
/reopen

2017-09-17 05:45 UTC, swiftdiaries commented
/reopen

2017-09-17 11:35 UTC, k82cn commented
@swiftdiaries  , please sign cla first :).

2017-09-17 18:40 UTC, swiftdiaries commented
@k82cn I have signed it, but for some reason the bot is not recognizing it.

2017-09-18 00:30 UTC, k82cn commented
@swiftdiaries , please check detail to see what happened :).

2017-09-18 00:30 UTC, k82cn commented on pkg/schedulercache/resource_info.go
> +	mem := rl[v1.ResourceMemory]
We need to check return value of map, some quest may only have cpu request.

2017-09-18 00:31 UTC, k82cn commented on pkg/schedulercache/resource_info.go
> +	r.Memory -= rr.Memory
we need to check the value of each resource, negative memory does not make sense.

2017-09-18 00:33 UTC, k82cn commented on pkg/schedulercache/resource_info.go
> +	return r.MilliCPU < rr.MilliCPU && r.Memory < rr.Memory
check nil

2017-09-18 00:33 UTC, k82cn commented on pkg/schedulercache/resource_info.go
> +	return (r.MilliCPU < rr.MilliCPU || math.Abs(rr.MilliCPU-r.MilliCPU) < 0.01) &&
check nil

2017-09-18 00:35 UTC, k82cn requested changes
Thanks very much ! that's the basic function what we want. Just some suggestion on safe checking, please help to add comments & unit test

2017-09-18 00:35 UTC, k82cn commented
BTW, please also squash/merge those commit into one.

2017-09-18 01:27 UTC, swiftdiaries commented
Thank you for the review @k82cn :) I'll add changes and update accordingly. I'll also try to add comments and unit tests.

2017-09-18 02:51 UTC, jinzhejz commented on pkg/schedulercache/resource_info.go
> +func CopyResource(r *Resource) *Resource {
suggest use `Clone()` as other xxx_info.go

2017-09-18 06:08 UTC, swiftdiaries commented
Closing this PR because of CLA issues and a messed up git history. I'll reopen a new one and submit again.

2017-09-18 06:08 UTC, closed without merging